server:
  host: "0.0.0.0"
  port: 8080

database:
  path: "./data/alfredo.db"

photos:
  dir: "./photos"

gcalendar:
  client_id: ""
  client_secret: ""
  refresh_token: ""

app:
  timezone: "America/Sao_Paulo"
